# Generated by Django 5.2.7 on 2025-11-21 03:13

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('red', 'Red'), ('white', 'White'), ('rose', 'Rose'), ('specialty', 'Specialty')], max_length=20)),
                ('is_vintage', models.BooleanField(default=False)),
                ('sweetness', models.CharField(choices=[('dry', 'Dry'), ('off-dry', 'Off dry'), ('sweet', 'Sweet'), ('very-sweet', 'Very sweet')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
        ),
        migrations.CreateModel(
            name='StoreWine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='winetracker.store')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='winetracker.wine')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('store', 'wine'), name='unique_store_wine')],
            },
        ),
    ]
