# Generated by Django 5.2.7 on 2025-11-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winetracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
