# Generated by Django 5.2.7 on 2025-11-21 05:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winetracker', '0002_alter_wine_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
